export const EV_FIELDS = [
  { key: 'marke', label: 'Marke', type: 'text' },
  { key: 'modell', label: 'Modell', type: 'text' },
  { key: 'batterie_netto', label: 'Batterie Netto (kWh)', type: 'number' },
  { key: 'laden_10_80_min', label: '10%–80% (min)', type: 'number' },
  { key: 'kwh_nach_70', label: 'kWh nach 70% (berechnet)', type: 'number', calc: true },
  { key: 'kwh_pro_min', label: 'kWh/min (berechnet)', type: 'number', calc: true },
  { key: 'max_ladeleistung', label: 'Max. Ladeleistung (kW)', type: 'number' },
  { key: 'anhaengelast', label: 'Anhängelast (kg)', type: 'number' },
  { key: 'wltp_reichweite', label: 'WLTP Reichweite (km)', type: 'number' },
  { key: 'wltp_verbrauch', label: 'WLTP Verbrauch (kWh/100km)', type: 'number' },
  { key: 'basis_preis', label: 'Basispreis (€)', type: 'number' },
  { key: 'hoechster_preis', label: 'Höchster Preis (€)', type: 'number' },
  { key: 'null_hundert', label: '0–100 (s)', type: 'number' },
  { key: 'ps', label: 'PS', type: 'number' },
  { key: 'top_speed', label: 'Top Speed (km/h)', type: 'number' },
  { key: 'volt', label: 'Volt', type: 'number' },
  { key: 'markteinfuehrung', label: 'Markteinführung', type: 'text' },
]

export const ICE_FIELDS = [
  { key: 'marke', label: 'Marke', type: 'text' },
  { key: 'modell', label: 'Modell', type: 'text' },
  { key: 'kraftstoff', label: 'Kraftstoff', type: 'text' },
  { key: 'hubraum_ccm', label: 'Hubraum (ccm)', type: 'number' },
  { key: 'zylinder', label: 'Zylinder', type: 'number' },
  { key: 'getriebe', label: 'Getriebe', type: 'text' },
  { key: 'ps', label: 'PS', type: 'number' },
  { key: 'null_hundert', label: '0–100 (s)', type: 'number' },
  { key: 'top_speed', label: 'Top Speed (km/h)', type: 'number' },
  { key: 'verbrauch_l100km', label: 'Verbrauch (l/100km)', type: 'number' },
  { key: 'co2_g_km', label: 'CO₂ (g/km)', type: 'number' },
  { key: 'anhaengelast', label: 'Anhängelast (kg)', type: 'number' },
  { key: 'basis_preis', label: 'Basispreis (€)', type: 'number' },
  { key: 'hoechster_preis', label: 'Höchster Preis (€)', type: 'number' },
  { key: 'markteinfuehrung', label: 'Markteinführung', type: 'text' },
]
