export const TRUCK_ADVISOR_MODELS = Object.freeze([
  {
    id: 'volvo-fl-electric',
    brand: 'Volvo',
    model: 'FL Electric',
    useCases: ['urban'],
    vehicleFormats: ['rigid'],
    trailerCapable: false,
    batteryKwh: 375,
    dcChargeKw: 150,
    energyConsumptionKwhPer100km: 95,
    purchasePriceEur: 310000,
    dieselEquivalentPriceEur: 140000,
    maxRangeKm: 220,
    maxPayloadT: 16,
    routeFit: ['stable', 'mixed', 'volatile'],
    chargeWindows: ['overnight', 'between_shifts'],
    returnToDepotFriendly: true,
    requiresDepotCharging: true,
    publicFastChargeCapable: false,
    chargingStandard: 'ccs',
    chargingMode: 'depot',
  },
  {
    id: 'renault-e-tech-d-wide',
    brand: 'Renault Trucks',
    model: 'E-Tech D Wide',
    useCases: ['urban', 'regional'],
    vehicleFormats: ['rigid'],
    trailerCapable: false,
    batteryKwh: 375,
    dcChargeKw: 150,
    energyConsumptionKwhPer100km: 105,
    purchasePriceEur: 320000,
    dieselEquivalentPriceEur: 150000,
    maxRangeKm: 260,
    maxPayloadT: 18,
    routeFit: ['stable', 'mixed', 'volatile'],
    chargeWindows: ['overnight', 'between_shifts'],
    returnToDepotFriendly: true,
    requiresDepotCharging: true,
    publicFastChargeCapable: true,
    chargingStandard: 'ccs',
    chargingMode: 'depotPublic',
  },
  {
    id: 'mercedes-eactros-300-400',
    brand: 'Mercedes-Benz',
    model: 'eActros 300/400',
    useCases: ['urban', 'regional'],
    vehicleFormats: ['rigid'],
    trailerCapable: false,
    batteryKwh: 448,
    dcChargeKw: 160,
    energyConsumptionKwhPer100km: 110,
    purchasePriceEur: 360000,
    dieselEquivalentPriceEur: 170000,
    maxRangeKm: 330,
    maxPayloadT: 20,
    routeFit: ['stable', 'mixed'],
    chargeWindows: ['overnight', 'between_shifts'],
    returnToDepotFriendly: true,
    requiresDepotCharging: true,
    publicFastChargeCapable: true,
    chargingStandard: 'ccs',
    chargingMode: 'depotPublic',
  },
  {
    id: 'volvo-fe-electric',
    brand: 'Volvo',
    model: 'FE Electric',
    useCases: ['urban'],
    vehicleFormats: ['rigid'],
    trailerCapable: false,
    batteryKwh: 376,
    dcChargeKw: 150,
    energyConsumptionKwhPer100km: 108,
    purchasePriceEur: 325000,
    dieselEquivalentPriceEur: 150000,
    maxRangeKm: 275,
    maxPayloadT: 17,
    routeFit: ['stable', 'mixed', 'volatile'],
    chargeWindows: ['overnight', 'between_shifts'],
    returnToDepotFriendly: true,
    requiresDepotCharging: true,
    publicFastChargeCapable: true,
    chargingStandard: 'ccs',
    chargingMode: 'depotPublic',
  },
  {
    id: 'volvo-fm-low-entry',
    brand: 'Volvo',
    model: 'FM Low Entry',
    useCases: ['urban', 'regional'],
    vehicleFormats: ['rigid'],
    trailerCapable: false,
    batteryKwh: 360,
    dcChargeKw: 250,
    energyConsumptionKwhPer100km: 115,
    purchasePriceEur: 340000,
    dieselEquivalentPriceEur: 165000,
    maxRangeKm: 200,
    maxPayloadT: 18,
    routeFit: ['stable', 'mixed', 'volatile'],
    chargeWindows: ['overnight', 'between_shifts'],
    returnToDepotFriendly: true,
    requiresDepotCharging: true,
    publicFastChargeCapable: true,
    chargingStandard: 'ccs',
    chargingMode: 'depotPublic',
  },
  {
    id: 'volvo-fm-electric',
    brand: 'Volvo',
    model: 'FM Electric',
    useCases: ['regional'],
    vehicleFormats: ['rigid', 'tractor'],
    trailerCapable: true,
    batteryKwh: 540,
    dcChargeKw: 250,
    energyConsumptionKwhPer100km: 125,
    purchasePriceEur: 420000,
    dieselEquivalentPriceEur: 190000,
    maxRangeKm: 380,
    maxPayloadT: 24,
    routeFit: ['stable', 'mixed'],
    chargeWindows: ['overnight', 'between_shifts'],
    returnToDepotFriendly: true,
    requiresDepotCharging: true,
    publicFastChargeCapable: true,
    chargingStandard: 'ccs',
    chargingMode: 'depotPublic',
  },
  {
    id: 'man-etgx',
    brand: 'MAN',
    model: 'eTGX',
    useCases: ['regional', 'longhaul'],
    vehicleFormats: ['tractor'],
    trailerCapable: true,
    batteryKwh: 534,
    dcChargeKw: 375,
    energyConsumptionKwhPer100km: 125,
    purchasePriceEur: 430000,
    dieselEquivalentPriceEur: 200000,
    maxRangeKm: 480,
    maxPayloadT: 24,
    routeFit: ['stable', 'mixed'],
    chargeWindows: ['between_shifts', 'tight'],
    returnToDepotFriendly: false,
    requiresDepotCharging: false,
    publicFastChargeCapable: true,
    chargingStandard: 'mcs',
    chargingMode: 'publicReady',
  },
  {
    id: 'renault-e-tech-t',
    brand: 'Renault Trucks',
    model: 'E-Tech T',
    useCases: ['regional'],
    vehicleFormats: ['tractor'],
    trailerCapable: true,
    batteryKwh: 540,
    dcChargeKw: 250,
    energyConsumptionKwhPer100km: 128,
    purchasePriceEur: 415000,
    dieselEquivalentPriceEur: 195000,
    maxRangeKm: 300,
    maxPayloadT: 24,
    routeFit: ['stable', 'mixed'],
    chargeWindows: ['between_shifts'],
    returnToDepotFriendly: true,
    requiresDepotCharging: false,
    publicFastChargeCapable: true,
    chargingStandard: 'ccs',
    chargingMode: 'depotPublic',
  },
  {
    id: 'daf-xd-electric',
    brand: 'DAF',
    model: 'XD Electric',
    useCases: ['urban', 'regional'],
    vehicleFormats: ['rigid', 'tractor'],
    trailerCapable: true,
    batteryKwh: 525,
    dcChargeKw: 325,
    energyConsumptionKwhPer100km: 122,
    purchasePriceEur: 405000,
    dieselEquivalentPriceEur: 185000,
    maxRangeKm: 500,
    maxPayloadT: 24,
    routeFit: ['stable', 'mixed'],
    chargeWindows: ['between_shifts', 'tight'],
    returnToDepotFriendly: true,
    requiresDepotCharging: false,
    publicFastChargeCapable: true,
    chargingStandard: 'ccs',
    chargingMode: 'publicReady',
  },
  {
    id: 'daf-xf-electric',
    brand: 'DAF',
    model: 'XF Electric',
    useCases: ['regional', 'longhaul'],
    vehicleFormats: ['tractor'],
    trailerCapable: true,
    batteryKwh: 525,
    dcChargeKw: 325,
    energyConsumptionKwhPer100km: 126,
    purchasePriceEur: 425000,
    dieselEquivalentPriceEur: 195000,
    maxRangeKm: 500,
    maxPayloadT: 24,
    routeFit: ['stable', 'mixed'],
    chargeWindows: ['between_shifts', 'tight'],
    returnToDepotFriendly: false,
    requiresDepotCharging: false,
    publicFastChargeCapable: true,
    chargingStandard: 'ccs',
    chargingMode: 'publicReady',
  },
  {
    id: 'scania-40r-bev',
    brand: 'Scania',
    model: '40 R BEV',
    useCases: ['regional', 'longhaul'],
    vehicleFormats: ['tractor'],
    trailerCapable: true,
    batteryKwh: 624,
    dcChargeKw: 375,
    energyConsumptionKwhPer100km: 128,
    purchasePriceEur: 445000,
    dieselEquivalentPriceEur: 205000,
    maxRangeKm: 500,
    maxPayloadT: 25,
    routeFit: ['stable', 'mixed'],
    chargeWindows: ['between_shifts', 'tight'],
    returnToDepotFriendly: false,
    requiresDepotCharging: false,
    publicFastChargeCapable: true,
    chargingStandard: 'mcs',
    chargingMode: 'publicReady',
  },
  {
    id: 'scania-45r-bev',
    brand: 'Scania',
    model: '45 R BEV',
    useCases: ['regional', 'longhaul'],
    vehicleFormats: ['tractor'],
    trailerCapable: true,
    batteryKwh: 728,
    dcChargeKw: 375,
    energyConsumptionKwhPer100km: 132,
    purchasePriceEur: 470000,
    dieselEquivalentPriceEur: 210000,
    maxRangeKm: 560,
    maxPayloadT: 25,
    routeFit: ['stable', 'mixed'],
    chargeWindows: ['between_shifts', 'tight'],
    returnToDepotFriendly: false,
    requiresDepotCharging: false,
    publicFastChargeCapable: true,
    chargingStandard: 'mcs',
    chargingMode: 'publicReady',
  },
  {
    id: 'mercedes-eactros-600',
    brand: 'Mercedes-Benz',
    model: 'eActros 600',
    useCases: ['longhaul'],
    vehicleFormats: ['tractor'],
    trailerCapable: true,
    batteryKwh: 621,
    dcChargeKw: 400,
    energyConsumptionKwhPer100km: 130,
    purchasePriceEur: 460000,
    dieselEquivalentPriceEur: 215000,
    maxRangeKm: 500,
    maxPayloadT: 25,
    routeFit: ['stable'],
    chargeWindows: ['between_shifts', 'tight'],
    returnToDepotFriendly: false,
    requiresDepotCharging: false,
    publicFastChargeCapable: true,
    chargingStandard: 'mcs',
    chargingMode: 'fastPriority',
  },
  {
    id: 'volvo-fh-aero-electric',
    brand: 'Volvo',
    model: 'FH Aero Electric',
    useCases: ['longhaul'],
    vehicleFormats: ['tractor'],
    trailerCapable: true,
    batteryKwh: 780,
    dcChargeKw: 375,
    energyConsumptionKwhPer100km: 129,
    purchasePriceEur: 455000,
    dieselEquivalentPriceEur: 210000,
    maxRangeKm: 520,
    maxPayloadT: 25,
    routeFit: ['stable'],
    chargeWindows: ['between_shifts', 'tight'],
    returnToDepotFriendly: false,
    requiresDepotCharging: false,
    publicFastChargeCapable: true,
    chargingStandard: 'mcs',
    chargingMode: 'fastPriority',
  },
])
